export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SEGMENT_NOT_FOUND: "SEGMENT_NOT_FOUND",
  INVALID_RISK_LEVEL: "INVALID_RISK_LEVEL",
  RISK_DOWNGRADE_BLOCKED: "RISK_DOWNGRADE_BLOCKED",
  MISSING_LAST_CHECKED_AT: "MISSING_LAST_CHECKED_AT"
} as const;
