export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SEGMENT_NOT_FOUND: "SEGMENT_NOT_FOUND",
  RISK_DOWNGRADE_BLOCKED: "RISK_DOWNGRADE_BLOCKED"
} as const;
